// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Queue, ServiceStub, SmartBucket, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  ADMIN_SERVICE: ServiceStub<import('../admin-service/index.js').default>;
  AI: Ai;
  AI_PROCESSING: Queue<import('../ai-processing-observer').Body>;
  ANALYTICS_SERVICE: ServiceStub<import('../analytics-service/index.js').default>;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  COMMUNICATION_SERVICE: ServiceStub<import('../communication-service/index.js').default>;
  COMMUNICATIONS_LOG: SmartBucket;
  COMPLIANCE_CHECKS: Queue<import('../compliance-observer').Body>;
  COMPLIANCE_SERVICE: ServiceStub<import('../compliance-service/index.js').default>;
  CUSTOMER_DATA: SmartBucket;
  CUSTOMER_SERVICE: ServiceStub<import('../customer-service/index.js').default>;
  CUSTOMERS_DB: SqlDatabase;
  EMAIL_SENDING: Queue<import('../email-sending-observer').Body>;
  INVOICE_SERVICE: ServiceStub<import('../invoice-service/index.js').default>;
  INVOICES_DB: SqlDatabase;
  logger: Logger;
  mem: KvCache;
  PAYMENT_PROCESSOR: ServiceStub<import('../payment-processor/index.js').default>;
  SMS_SENDING: Queue<import('../sms-sending-observer').Body>;
  tracer: Tracer;
  VOICE_CALLS: Queue<import('../voice-calls-observer').Body>;
}
